WPManageNinja/fluent-smtp

- README.md
- readme.txt
- resources/admin/Modules/Misc/Support.vue
Just a few minor typo/capitalization fixes, e.g. `Github` -> `GitHub`
> Fix typos/capitalization

- README.md
- app/Services/Mailer/Providers/config.php
- language/fluent-smtp.pot
- readme.txt
- resources/admin/Modules/Settings/Partials/Providers/Gmail.vue
- resources/admin/Modules/Settings/Partials/Providers/PepiPost.vue
- resources/admin/Modules/Settings/Partials/Providers/SendInBlue.vue
Went in to change `Ses` to `SES` and stumbled upon some more. These changes should only affect display code, no functionality.
> Fix branding typos

- app/Functions/pluggable.php
The pluggable function is missing a very important WordPress filter `pre_wp_mail`.
This filter is often the only way to short-circuit the sending of emails that you dont want to got out. 
A good example of this might be a plugin thats does not offer dedicated hooks to control inbuilt email functionality. 
`pre_wp_mail` is often the last resort here to regain some control and customize some behaviour. 
I cant see any upside in removing this filter from the the pluggable function so please consider adding it back in. 
This PR is an exact replica of how the filter works inside the default `wp_mail()` function provided by WordPress
> Respect provided filters and functionality of the original wp_mail() function

- app/Hooks/Handlers/AdminMenuHandler.php
- app/Http/Controllers/SettingsController.php
As discussed in issue #44, this pull request will hide and block the installation of plugins from the support page when DISALLOW_FILE_MODS is defined and not set to false.
> Disable recommended plugin installation when DISALLOW_FILE_MODS is defined

- package.json
- resources/admin/Bits/FluentMail.js
- resources/admin/Modules/Logger/Logs.vue
fixes #7 where "Date-Time" column in "Email Logs" would not format for the user's locale.
This update uses dayjs's `dayjs.extend(localizedFormat)` function to allow dates to automatically format for the user's locale.  This mostly just replaces the hard-coded date time format with a format that is locale-aware.
Note: the package.json file now includes build scripts for anyone who doesn't use npx.  `npm start` to build and watch with webpack 5, `npm run prod` to build in production mode (webpack 5)
> I propose this fix for issue #7

- app/Services/Mailer/Providers/Mailgun/Handler.php
Mailgun handler assumed HTML emails.   It should inspect the content type and set text or html body param appropriately.
> Mailgun: fix sending plain text emails

- app/Services/Mailer/Providers/config.php
- resources/admin/Modules/Misc/Docs.vue
Some of the documentation links doesn't have the target="blank" attribute.
> Added target="_blank" in the documentation links

- database/FluentMailDBMigrator.php
The `get_sites()` function returns only 100 sites by default.  
https://developer.wordpress.org/reference/classes/wp_site_query/__construct/#parameters  
> 'number'
> (int) Maximum number of sites to retrieve. Default 100.
If a multisite has over 100 sites the activation hook will not create the database tables needed for email logging for any site over the first 100 returned.
This change adds the `number` key to the `$args` array passed into the `get_sites()` call, with the value being set to the blog count returned from `get_blog_count()`. 
Side note, `get_blog_count()` shouldn't need the current network ID passed into it because it defaults to the current network and that is also what the `get_sites()` call is doing.
> Add number arg to the get_sites() call.

- resources/admin/Modules/Settings/Partials/_ConnectionSelector.vue
- resources/scss/fluent-mail-admin.scss
- resources/scss/vendor.scss
The current connection grid has a few problems that I wanted to fix:
- some logos take up more space
- tall logos get stretched out of proportion
- with multiple rows, we get spacing between rows, but not between items / columns
Current:
New:
> Update connections grid styles

- .gitignore
Sublime Text stores Project metadata in `name.sublime-project` and  `name.sublime-workspace` files. These should never be committed. So to keep them from permanently being in git's WIP / Unstaged Files category we should git-ignore them.
> Ignore *.sublime-*

- resources/scss/vendor.scss
The CSS code breaks the checkbox styles on every connection page. Screenshot: https://prnt.sc/xfObSLpyGIQv
Removing the codes fixes the styles. Screenshot: https://prnt.sc/j-Xrxt3PsHDA
> Fixed UI issue on add connection page

- app/Functions/helpers.php
- app/Hooks/Handlers/AdminMenuHandler.php
Add the FLUENTMAIL_SIMULATE_EMAILS constant to enforce simulation mode via wp-config.php. This especially helps with cases where a site is being cloned to a staging/development install and might start sending emails before the site owner can visit the wp-admin to enable simulation mode. For example, when email automations are configured in FluentCRM, one doesn't want a staging site sending out emails to customers.
The admin-bar notification is also triggered so that admins know that email sending is disabled.
> allow disabling emails via wp-config.php

- includes/OAuth2Provider.php
The function `http_build_query()` does not accept a `null` value anymore for the `$numeric_prefix` argument. Replacing the `null` with an empty string resolves the problem.
```
PHP Deprecated:  http_build_query(): Passing null to parameter #2 ($numeric_prefix) of type string is deprecated in /wp-content/plugins/fluent-smtp/includes/OAuth2Provider.php on line 103
```
> Fixed deprecated null argument in PHP 8.1

- app/Http/Controllers/SettingsController.php
Using a strong, generated password we couldn't get a test email to send. It resulted in authentication error. Looking at the stored password we saw that it was truncated at a '<' character. Found the field was being passed through sanitize_text_field in the settings controller. 
Causes the following issues:
* Any HTML entities in password end up encoded.
* A password with < will be truncated (strip_tags function)
* A password < and > will have them and any text in between removed (strip_tags function).
update_option() will handle SQL escapes in the settings model store function.
> Excluding password from sanitize_text_field()

- app/Services/Mailer/Providers/SendInBlue/Handler.php
Sendinblue now brevo, so they update their API endpoints, I believe you also need to update. Here is new API details https://developers.brevo.com/reference/sendtransacemail
> update API endpoint new domain of brevo formarly Sendinblue

- app/Services/Mailer/Providers/Mailgun/Handler.php
The Mailgun Service Handler does not currently check for or honor custom headers that have been set in phpmailer.  This caused the "list-unsubscribe" header from FluentCRM to be lost when sending via Mailgun.
Used and slightly modified code from Elastic Mail handler to keep coding consistent to enable this in the Mailgun Handler.
> Mailgun - enable custom headers (list-unsubscribe)

- resources/scss/fluent-mail-admin.scss
> Improvement: Text is going outside the box.

- app/Services/Mailer/Providers/SparkPost/Handler.php
This commit addresses two key issues with the SparkPost integration in FluentSMTP:
1. **Correct Recipient Address Handling:**
- Added a new `getTo()` method to properly set the `recipients` field in the SparkPost request body.
- Previously, the recipient address was incorrectly set to the sender's address, causing emails to fail or be misdirected.
- The `getTo()` method now retrieves the intended recipient addresses from the parameters, ensuring accurate delivery.
2. **Fix Content Headers Format:**
- Adjusted `content.headers` to be structured as a JSON object instead of an array, aligning with SparkPost API requirements.
- This change resolves #221 and #166 the `json_array` to `json_object` error that occurred when sending emails. 
3. **Adjust Sandbox Mode:**
- Set `sandbox` to `false` …
> Fix SparkPost integration: correct recipient address handling and content headers format

- app/Functions/helpers.php
By using this code the user can use an associative array for $attachment. $key is used as filename, while $value is the path. Will not cause issues for users that used indexed arrays. Took the code from native wp_mail and inserted it here. Worked well by testing on my machine.
> Add name to attachment file

- app/Hooks/Handlers/AdminMenuHandler.php
- app/Http/Controllers/SettingsController.php
- app/Services/Mailer/Providers/config.php
- resources/admin/Modules/Dashboard/Charts/Emails.vue
- resources/admin/Modules/Logger/LogFilter.vue
- resources/admin/Modules/Logger/LogViewer.vue
- resources/admin/Modules/Logger/Logs.vue
- resources/admin/Modules/Misc/Docs.vue
- resources/admin/Modules/Misc/Support.vue
- resources/admin/Modules/NotificationSettings/NotificationManager.vue
- resources/admin/Modules/NotificationSettings/_EmailSummaryForm.vue
- resources/admin/Modules/Settings/Partials/Providers/Smtp.vue
- resources/admin/Modules/Settings/Partials/_ConnectionSelector.vue
- resources/admin/Modules/Test/Test.vue
- resources/admin/Pieces/Confirm.vue
- resources/admin/Pieces/_Subscrbe.vue
This PR improves the localization functionality of multiple strings so that they are translatable (and will appear on translate.wordpress.org).  Some strings still show in English only in the frontend of the plugin
Please check my code if I made any errors and I try to contribute more if I find more strings.
Thanks!
> Improve localization

- app/Services/Mailer/Providers/config.php
- language/fluent-smtp.pot
Added ap-northeast-3, Asia Pacific (Osaka) regions for Amazon SES.
closes #304
> Add ap-northeast-3 (Asia Pacific (Osaka)) region

- app/Services/Mailer/Providers/Smtp2Go/Handler.php
Updated the import statement in `app/Services/Mailer/Providers/Smtp2Go/Handler.php` to use `Smtp2Go\ValidatorTrait` instead of `SendGrid\ValidatorTrait`, ensuring the correct validation trait is used for the SMTP2Go handler.
> fix:removed-sendgrid-validator-from-smtp2go-handler

- app/Services/Mailer/BaseHandler.php
`get_error_messages()` is basically the same message as `$message`, while `get_error_data()` provides useful information why an API call has an error. Most providers already put the response data as the WP_Error data, so no other changes should be necessary.
> Update error handling of BaseHandler
